<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPYxCovg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPYxCovg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPYxCovg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPYxCovg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPYxCovg\App_KernelDevDebugContainer([
    'container.build_hash' => 'PYxCovg',
    'container.build_id' => '77ff84cf',
    'container.build_time' => 1695286931,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPYxCovg');
